# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotodo < Formula
  desc "A tiny, delicate todo CLI written in Go"
  homepage "https://github.com/ethanbao27/gotodo"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanbao27/gotodo/releases/download/v1.0.6/gotodo_1.0.6_darwin_amd64.tar.gz"
      sha256 "7ab8a2a568939c33bd5b228c8fa35c12bca883cb1d038ea9dfef8299f616837b"

      def install
        bin.install "gotodo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanbao27/gotodo/releases/download/v1.0.6/gotodo_1.0.6_darwin_arm64.tar.gz"
      sha256 "9690274ed283998b777a42282bc0f947bd9edb488a4f61d61d96fa8dad16be6e"

      def install
        bin.install "gotodo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanbao27/gotodo/releases/download/v1.0.6/gotodo_1.0.6_linux_amd64.tar.gz"
      sha256 "94e064154b1ad5d5f6aab6e5b8761fb81067eab486475a636713e0b4e4d9536d"
      def install
        bin.install "gotodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanbao27/gotodo/releases/download/v1.0.6/gotodo_1.0.6_linux_arm64.tar.gz"
      sha256 "9ff564e381ca928e83bae7a35a970d4d6be1c9f042e942a4fd8180bc6f27ac80"
      def install
        bin.install "gotodo"
      end
    end
  end

  test do
    system "#{bin}/gotodo", "--version"
    system "#{bin}/gotodo", "--help"
  end
end
